# Generated by Django 5.1 on 2024-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_description_job_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='details_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
