# Generated by Django 5.1 on 2024-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_details_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
